### ISSUE TITLE
Upload a mix of photo's and video's like facebook 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox-feature-requests#166]
Hello :) 

it would be awesome, if we could upload a mixture of Photo's and video's like they have on facebook :)

**Comment by Data66PF** [comment]
We need to be careful. Last time we opened a feature request area, we started getting all kinds of "just like facebook" requests and then a lot of complaints due to those. We don't want to clone Facebook. We want new ideas that are not copying something else but are extending our product for all clients in a way that make it unique.
