### ISSUE TITLE
adding Friend notifications wrong phrase

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox-feature-requests#24]
_From @aakash83 on January 21, 2016 13:13_

tested on stage.phpfox.com 

when we send  a friend request to a member and  he/she accepts it  then the notification we get  says" He/ she added  you as a friend " it should   be  like  " he/she  accepted your  friend request".

_Copied from original issue: moxi9/phpfox#985_

**Comment by Data66PF** [comment]
IMO this is fine as it is as phrases are easily managed in the phrase manager and we will have clients that like it the way it is, some that change it to something completely different, and some that want it like you mention. The best solution is for each client to use the phrase manager and change it how you want it. IMO, this is working as designed.

**Comment by optiroot** [comment]
I agree with Data66, because it is similiar to so much other things. Like the phrase "friend", to do an example. If I'd like to create an Intranet for my team, I just need to change "friend" with "co-worker" or anything that I need. Obviously this is purely an example, I don't think someone will ever do this; but the function of this thing is simple: you don't even need to be a developer, just change the phrase and you transform in some-way your Social Network in a full-functional-intranet.
