### ISSUE TITLE
Staff should not be able see that site is by phpfox

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox-feature-requests#285]
Prior to version 4.x.x staff member did not have access to see that the site is run on phpfox. Bring this feature back.

**Comment by neil96** [comment]
Could you tell us more detail?

**Comment by prepperz** [comment]
Go to the homepage and right click on browser and view source. Control-F then search for phpfox. 

There are 14 instances that says it is a phpfox site. People should not be able to see any evidence that it's a phpfox site in the view source.

In v3.8.x, this was one of the very important aspects of the script.

**Comment by neil96** [comment]
They're directory name of the apps. If you'd like to hide these names, you can enable bundle js/css. The static files will compress and load from another directory.

**Comment by prepperz** [comment]
IN v3.8.x..x it doesn't show any indication of phpfox by default whether the js/cc are compressed or not.

**Comment by prepperz** [comment]
Also this a not a duplicate of the other. Just take a look a v3.8 and you'll see what I mean.

**Comment by phpfoxaccount** [comment]
@prepperz : it's nothing to do with phpFox branding in source code with core script. In fact, there is no phpFox in "core" if you use default script.
The texts you mention are from Application ID, which are usually named by 3rd parties including some phpFox to differ with others. They usually include their brand name in ID. If you choose to use these applications, the name will be displayed for sure. Ex. if other 3rd party names their products as phpFox_3rd_name_ID, it is shown there. Core has nothing to do in this case.
That's why we provide Bundle JS/CSS to compress these files, which helps to hide Application ID in path when viewing source code.

**Comment by prepperz** [comment]
That's on the default phpfox install
