### ISSUE TITLE
Reverting Theme Displays Default Phpfox Logo @ Fav icon

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#30]
Reverting a theme displays the phpfox default logo and fav icon. WE definitely don't want this to show in a production environment. It would be nice to have phpfox use a default logo & fav icon from a set directory. This way the site admin will always have their own logo & fav icon displayed during reverts or resets.

**Comment by Data66PF** [comment]
So you would like a way for the site admin to upload a sitewide favicon and logo that would be used in all themes and would be set as the site's default logo and favicon. 

I think most would also like the ability to use different logos for different themes so it would maybe need a setting to "enable in all themes" and a way to choose other logos for other themes. I've seen clients put different colored logos, for example, for different themes.

**Comment by lueung** [comment]
I just roll with it as long as it doesn't revert to the default php logos and fav icon on a production server. :)

**Comment by Data66PF** [comment]
Since we say not to use the bootstrap with any edits as it must be reverted and restored, we always recommend the first step for your site is to make a new theme and only work in that. I don't think this is needed because we say that the default will have to be reverted and to use a custom.

Unless you are saying that you are reverting your custom themes. Is that what you are doing?

**Comment by darksolar1** [comment]
That post was made a while back while I was just getting back into phpfox and thought that the default theme would be displayed by default on the front end every time it reverts.  I've come to realize that's not the case. So I'll close this.
