### ISSUE TITLE
Request Choice of username or full name only

### ISSUE THREAD

**Issue by vanucci** [moxi9/phpfox-feature-requests#38]
Idea

Have the ability on the sign up page to either have full name or user name only. 
Only option at the moment is to disable username. Be great to have option to pick one or the other.

**Comment by Data66PF** [comment]
This has been requested several times and it seems a good feature. However, we need to know how to handle this.

1. The fullname is used throughout the site to show what this user posts, etc. If no fullname is entered, the only thing that could display is the username and this makes for security issues as it's not good to display the username since that can be used to log in. 

Do we:

A. Allow the user to change the fullname right when they first log in to the site?
B. Allow the site owner to select a default displayed name until the user picks one?
C. Set a random displayed name for the new user until they change it?

Which one of those options or what is your idea? Noting that using username throughout the site can leave for security and privacy issues for those that don't want their private username shown?

**Comment by vanucci** [comment]
I suppose username and then display name would be the better route. 
So allow user to set a login name ( username ) and then a display name to be shown aroudn the site.

**Comment by Data66PF** [comment]
The fullname is the displayname though. It is just a difference in the phrase.

**Comment by vanucci** [comment]
So on that concept, i can change the full name phrase to soemthing else then ?

**Comment by Data66PF** [comment]
You could just use the setting in admincp at admincp/setting/edit/?module-id=user for Display or Full Name that allows you to change it from Full Name to Display name. That setting was added in v3 early on due to a feature request as users got confused with full name and clients wanted the option.

**Comment by vanucci** [comment]
Im lost  now, I dont want to have the phrase full name at all. Would this be achievable via phrase manager ?

**Comment by Data66PF** [comment]
As we said, just change the setting to Display name. It will then not show Full name. If you mean you want to completely disable the Display name/ Full name field, then this feature request would be for that and to have the user only using a username instead, which would not be secure as it would show their log in name throughout the site. Is that what you intended?

Right now, via the setting I showed you, you can change the Full Name to show as Display Name. That is what shows when users post and interact on the site.
