### ISSUE TITLE
Statistic for reviews

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#69]
Currently, on app’s posting and developer’s profile page, it only displays the list of reviews on the right column. It would be better if also displaying the statistic of reviews/rating such as: the total number of reviews, the average rating point, etc.

**Comment by Data66PF** [comment]
This feature request area was intended for core features and not really for store things. We will have to discuss if we will allow the requests here in the future. 

Do you have a screen shot of what you envision for this? I'm still not sure we will keep these feature requests here since they are not for our core product.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, please send us a ticket with details for the things you suggest for our store. You can reach us in the new client area, https://clients.phpfox.com/ . We do appreciate improvement ideas and did have a lot on our list to improve too.
