### ISSUE TITLE
Manually grant product licenses to clients

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox-feature-requests#72]
Some clients have already bought V4 modules on a developer’s website. Later on, those modules have been transferred to apps and published available on store.phpfox.com. So is there anyway to verify those clients as the people who already purchased those apps? So they can provide review on associated products when needed. Maybe a new function for developer manually grant product licences to any client would be helpful.

**Comment by Data66PF** [comment]
We had discussed this internally before. I am not for doing this as it can lead to fake reviews when developers need reviews and then boost the numbers. We put the policy in place for users to only review purchases at the store in order to avoid issues with fake reviews that we had in the old store.

**Comment by Data66PF** [comment]
I suppose the developer could give the client a refund of the original purchase so they can then go purchase the app. This would solve the issue without compromising the store review system.

**Comment by Data66PF** [comment]
As this request area was intended only for core feature requests, please send us a ticket with details for the things you suggest for our store. You can reach us in the new client area, https://clients.phpfox.com/ . We do appreciate improvement ideas and did have a lot on our list to improve too.
