### ISSUE TITLE
v4.3 forum search all forums including pages forums

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox-feature-requests#83]
I see that in the forum search feature that it only shows options to search the main forum and this forum. However, it left out the ability to search all forums including all the pages forums.

**Comment by Data66PF** [comment]
Pages and groups are made to be self contained. Due to many needing specific privacy for pages and groups, the search really shouldn't pick up those things in a search. I've not tested to make sure other pages/groups items are not included in the global search though. 

I think you would need a bigger feature for this so that it would include an option in the page/group for the admin of that page/group to "include discussions in global search". 

This is best done by a third party developer.

**Comment by lueung** [comment]
I believe that this would be a core opportunity to tap into the resources of these pages that are created. Depending on the site it may not even be geared toward pravate stuff @ all so to toss everyone in in the same category is really just missing the boat.
