### ISSUE TITLE
Rename original photo when uploaded

### ISSUE THREAD

**Issue by kosytedy** [moxi9/phpfox-feature-requests#91]
It looks very messy for images uploaded by users to have names like "img_1244976_2016_03_13.jpg". It would be nice if it would be renamed (in case of url link to the photo) and the name also hidden from feeds, timelines, etc. This will clean and improve the social network.

**Comment by kosytedy** [comment]
I mean for phpfox version 4

**Comment by Data66PF** [comment]
We used to have a setting for this. It does require the server to support this sort of thing. I believe it was removed due to those sort of issues. I will ask how feasible it is to bring this back. Otherwise, users can already edit their photo names by clicking Edit and renaming it themselves for now.

**Comment by kosytedy** [comment]
Please, it would be great to fix this. I've been amazed how creative and innovative Phpfox developers are, I really do appreciate your efforts.
